services:
  mysql:
    platform: linux/amd64
    image: mysql
    restart: always
    env_file: ./db/.env.prod
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --init-connect='SET NAMES utf8mb4'
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - http
  back:
    platform: linux/amd64
    image: ymh3190/http-back
    env_file: ./backend/.env.prod
    restart: on-failure
    expose:
      - 4000
    networks:
      - http
  front:
    platform: linux/amd64
    image: ymh3190/http-front
    env_file: ./frontend/.env.prod
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/views:/app/views
    expose:
      - 3000
    networks:
      - http
  nginx:
    platform: linux/amd64
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8080:8080
    expose:
      - 8080
    networks:
      - http

networks:
  http:
