services:
  dev-db:
    image: mysql
    restart: always
    env_file: ./db/.env
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command로는 한글 깨짐이 해결안되고 마운트로 해결함
    # 아닐 수도 잇음
    # command: 
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - 3307:3306
    networks:
      - http
  test-db:
    image: mysql
    restart: always
    env_file: ./db/.env.test
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - http
  # back
  test-back:
    build: ./backend
    env_file: ./backend/.env.test
    restart: on-failure
    expose:
      - 4000
    networks:
      - http
  back:
    platform: linux/amd64
    build: ./backend
  # front    
  test-front:
    build: ./frontend
    env_file: ./frontend/.env.test
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/views:/app/views
    expose:
      - 3000
    networks:
      - http
  front:
    platform: linux/amd64
    build: ./frontend
  # nginx
  dev-nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - http
    extra_hosts:
      - "host.docker.internal:host-gateway"
  test-nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.test.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    networks:
      - http

networks:
  http:
