services:
  dev-db:
    image: mysql
    restart: always
    env_file: ./db/.env
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command로는 한글 깨짐이 해결안되고 마운트로 해결함
    # command: 
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - http
  test-db:
    image: mysql
    restart: always
    env_file: ./db/.env.test
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3309:3306
    expose:
      - 3306
    networks:
      - http
  # back
  test-back:
    build: ./backend
    env_file: ./backend/.env.test
    restart: on-failure
    expose:
      - 4000
    networks:
      - http
  back:
    platform: linux/amd64
    build: ./backend
    environment:
      - PORT=4000
      - WATCH=
      - DB_HOST=db
      - DB_USER=admin
      - DB_DATABASE=http
      - DB_PORT=3306
      - DB_PASSWORD=1
      - JWT_SECRET=B7ADFBBAFA67DCE3ECCEE5C54E58A
    restart: on-failure
    expose:
      - 4000
    networks:
      - http
  # front    
  test-front:
    build: ./frontend
    env_file: ./frontend/.env.test
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/views:/app/views
    expose:
      - 3000
    networks:
      - http
  front:
    platform: linux/amd64
    build: ./frontend
    environment:
      - PORT=3000
      - WATCH=
      - BE_HOST=back
      - BE_PORT=4000
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/views:/app/views
  # nginx
  dev-nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - http
    extra_hosts:
      - "host.docker.internal:host-gateway"
  test-nginx:
    image: nginx
    volumes:
      - ./nginx/default.test.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - http

networks:
  http:
