services:
  db:
    build: ./db
    image: db
    container_name: db
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - internalnet
      
  back:
    build: ./backend
    image: back
    container_name: back
    env_file: ./.env
    restart: on-failure
    ports:
      - ${BE_PORT}:${BE_PORT}
    expose:
      - ${BE_PORT}
    depends_on:
      - db
    networks:
      - internalnet

  front:
    build: ./frontend
    image: front
    container_name: front
    env_file: ./.env
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static
    ports:
      - ${FE_PORT}:${FE_PORT}
    expose:
      - ${FE_PORT}
    depends_on:
      - back
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge