services:
  dev-db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_DATABASE=http
      - MYSQL_PASSWORD=admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - 3307:3306
    networks:
      - http
  dev-nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html/dist
    ports:
      - 80:80
    networks:
      - http
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  http:
