export const pageDOMs = {};
pageDOMs['client-page']=document.querySelector('section#client.page');
pageDOMs['commodity-page']=document.querySelector('section#commodity.page');
pageDOMs['image-page']=document.querySelector('section#image.page');
pageDOMs['index-page']=document.querySelector('section#index.page');
pageDOMs['product-page']=document.querySelector('section#product.page');
pageDOMs['signin-page']=document.querySelector('section#signin.page');
pageDOMs['signup-page']=document.querySelector('section#signup.page');
pageDOMs['tank-page']=document.querySelector('section#tank.page');
pageDOMs['user-page']=document.querySelector('section#user.page');
pageDOMs['video-page']=document.querySelector('section#video.page');
export const formDOMs = {};
formDOMs['search-client']=document.querySelector('form#search.client');
formDOMs['saveUpdate-client']=document.querySelector('form#saveUpdate.client');
formDOMs['search-commodity']=document.querySelector('form#search.commodity');
formDOMs['saveUpdate-commodity']=document.querySelector('form#saveUpdate.commodity');
formDOMs['search-product']=document.querySelector('form#search.product');
formDOMs['saveUpdate-product']=document.querySelector('form#saveUpdate.product');
formDOMs['signin-signin']=document.querySelector('form#signin.signin');
formDOMs['signup-signup']=document.querySelector('form#signup.signup');
formDOMs['search-tank']=document.querySelector('form#search.tank');
formDOMs['saveUpdate-tank']=document.querySelector('form#saveUpdate.tank');
formDOMs['search-user']=document.querySelector('form#search.user');
formDOMs['saveUpdate-user']=document.querySelector('form#saveUpdate.user');
formDOMs['search-header']=document.querySelector('form#search.header');
export const divDOMs = {};
divDOMs['list-client']=document.querySelector('div#list.client');
divDOMs['list-commodity']=document.querySelector('div#list.commodity');
divDOMs['list-product']=document.querySelector('div#list.product');
divDOMs['list-tank']=document.querySelector('div#list.tank');
divDOMs['list-user']=document.querySelector('div#list.user');
export const inputDOMs = {};
inputDOMs['name-popup']=document.querySelector('input#name.popup')
inputDOMs['company-header']=document.querySelector('input#company.header')
inputDOMs['company-detail']=document.querySelector('input#company.detail')
inputDOMs['address-detail']=document.querySelector('input#address.detail')
inputDOMs['tel-detail']=document.querySelector('input#tel.detail')
inputDOMs['fax-detail']=document.querySelector('input#fax.detail')
inputDOMs['tax_no-detail']=document.querySelector('input#tax_no.detail')
inputDOMs['corp_no-detail']=document.querySelector('input#corp_no.detail')
inputDOMs['manager_name-detail']=document.querySelector('input#manager_name.detail')
inputDOMs['manager_tel-detail']=document.querySelector('input#manager_tel.detail')
inputDOMs['ceo_name-detail']=document.querySelector('input#ceo_name.detail')
inputDOMs['ceo_tel-detail']=document.querySelector('input#ceo_tel.detail')
inputDOMs['name-header']=document.querySelector('input#name.header')
inputDOMs['name-detail']=document.querySelector('input#name.detail')
inputDOMs['unit-detail']=document.querySelector('input#unit.detail')
inputDOMs['price-detail']=document.querySelector('input#price.detail')
inputDOMs['specification-detail']=document.querySelector('input#specification.detail')
inputDOMs['stock-detail']=document.querySelector('input#stock.detail')
inputDOMs['temp-header']=document.querySelector('input#temp.header')
inputDOMs['name-detail']=document.querySelector('input#name.detail')
inputDOMs['username-signin']=document.querySelector('input#username.signin')
inputDOMs['password-signin']=document.querySelector('input#password.signin')
inputDOMs['username-signup']=document.querySelector('input#username.signup')
inputDOMs['password-signup']=document.querySelector('input#password.signup')
inputDOMs['rePassword-signup']=document.querySelector('input#rePassword.signup')
inputDOMs['name-detail']=document.querySelector('input#name.detail')
inputDOMs['address-detail']=document.querySelector('input#address.detail')
inputDOMs['department-header']=document.querySelector('input#department.header')
inputDOMs['name-header']=document.querySelector('input#name.header')
inputDOMs['name-detail']=document.querySelector('input#name.detail')
inputDOMs['address-detail']=document.querySelector('input#address.detail')
inputDOMs['name-header']=document.querySelector('input#name.header')
export const selectDOMs = {};
selectDOMs['type-header']=document.querySelector('select#type.header')
selectDOMs['type-detail']=document.querySelector('select#type.detail')
selectDOMs['type-header']=document.querySelector('select#type.header')
selectDOMs['item_id-header']=document.querySelector('select#item_id.header')
selectDOMs['type-detail']=document.querySelector('select#type.detail')
selectDOMs['item_id-detail']=document.querySelector('select#item_id.detail')
selectDOMs['item-header']=document.querySelector('select#item.header')
selectDOMs['item-header']=document.querySelector('select#item.header')
export const textareaDOMs = {};
textareaDOMs['comment-detail']=document.querySelector('textarea#comment.detail')
export const checkboxDOMs = {};
checkboxDOMs['fired-header']=document.querySelector('input#fired.header')
export const btnDOMs = {};
btnDOMs['search-header']=document.querySelector('button#search.header')
btnDOMs['print-header']=document.querySelector('button#print.header')
btnDOMs['create-detail']=document.querySelector('button#create.detail')
btnDOMs['save-detail']=document.querySelector('button#save.detail')
btnDOMs['delete-detail']=document.querySelector('button#delete.detail')
btnDOMs['search-header']=document.querySelector('button#search.header')
btnDOMs['print-header']=document.querySelector('button#print.header')
btnDOMs['create-detail']=document.querySelector('button#create.detail')
btnDOMs['save-detail']=document.querySelector('button#save.detail')
btnDOMs['delete-detail']=document.querySelector('button#delete.detail')
btnDOMs['addition-contents']=document.querySelector('button#addition.contents')
btnDOMs['search-header']=document.querySelector('button#search.header')
btnDOMs['print-header']=document.querySelector('button#print.header')
btnDOMs['create-detail']=document.querySelector('button#create.detail')
btnDOMs['save-detail']=document.querySelector('button#save.detail')
btnDOMs['delete-detail']=document.querySelector('button#delete.detail')
btnDOMs['search-header']=document.querySelector('button#search.header')
btnDOMs['print-header']=document.querySelector('button#print.header')
btnDOMs['create-detail']=document.querySelector('button#create.detail')
btnDOMs['save-detail']=document.querySelector('button#save.detail')
btnDOMs['delete-detail']=document.querySelector('button#delete.detail')
btnDOMs['search-header']=document.querySelector('button#search.header')
btnDOMs['print-header']=document.querySelector('button#print.header')
btnDOMs['create-detail']=document.querySelector('button#create.detail')
btnDOMs['save-detail']=document.querySelector('button#save.detail')
btnDOMs['delete-detail']=document.querySelector('button#delete.detail')
btnDOMs['addition-contents']=document.querySelector('button#addition.contents')
export const iconDOMs = {};
iconDOMs['search-header']=document.querySelector('button#search.header > i')
iconDOMs['print-header']=document.querySelector('button#print.header > i')
iconDOMs['create-detail']=document.querySelector('button#create.detail > i')
iconDOMs['save-detail']=document.querySelector('button#save.detail > i')
iconDOMs['delete-detail']=document.querySelector('button#delete.detail > i')
iconDOMs['search-header']=document.querySelector('button#search.header > i')
iconDOMs['print-header']=document.querySelector('button#print.header > i')
iconDOMs['create-detail']=document.querySelector('button#create.detail > i')
iconDOMs['save-detail']=document.querySelector('button#save.detail > i')
iconDOMs['delete-detail']=document.querySelector('button#delete.detail > i')
iconDOMs['addition-contents']=document.querySelector('button#addition.contents > i')
iconDOMs['search-header']=document.querySelector('button#search.header > i')
iconDOMs['print-header']=document.querySelector('button#print.header > i')
iconDOMs['create-detail']=document.querySelector('button#create.detail > i')
iconDOMs['save-detail']=document.querySelector('button#save.detail > i')
iconDOMs['delete-detail']=document.querySelector('button#delete.detail > i')
iconDOMs['search-header']=document.querySelector('button#search.header > i')
iconDOMs['print-header']=document.querySelector('button#print.header > i')
iconDOMs['create-detail']=document.querySelector('button#create.detail > i')
iconDOMs['save-detail']=document.querySelector('button#save.detail > i')
iconDOMs['delete-detail']=document.querySelector('button#delete.detail > i')
iconDOMs['search-header']=document.querySelector('button#search.header > i')
iconDOMs['print-header']=document.querySelector('button#print.header > i')
iconDOMs['create-detail']=document.querySelector('button#create.detail > i')
iconDOMs['save-detail']=document.querySelector('button#save.detail > i')
iconDOMs['delete-detail']=document.querySelector('button#delete.detail > i')
iconDOMs['addition-contents']=document.querySelector('button#addition.contents > i')
export const partialDOMs = {};
export const tempDOMs = {};
tempDOMs['controls-contents']=document.querySelector('template#controls.contents')
tempDOMs['controls-contents']=document.querySelector('template#controls.contents')
export const popupDOMs = {};
popupDOMs['genre-contents']=document.querySelector('form#genre.contents')
popupDOMs['genre-contents']=document.querySelector('form#genre.contents')
